### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [hagimoto0943/goki-network#89]
@hagimoto0943 
MVPリリースお疲れ様でした！下記の観点でレビューいたします。
```
1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

### READMEから課題解決する実装がされているか&動いている
MVP部分は実装されていますね！
就活目線で言うと、ActionCableの実装など少し高度な実装が技術的にある方が良いのでぜひ実装するようにしてください。

### 静的コードチェックが入っている
rubocopを導入してコードチェックを通しておくようにしましょう。
これで最低限のコードの見た目は担保できるので、必要に応じてrubocopの設定は調整するようにすると良いです！

### 就活において十分な技術力を示せる機能を実装しているか
商品表示ページなどAPIを利用している部分もありますが、CRUD処理がメイン機能に見えるので下記の内容はぜひ実装しましょう。
- fight情報周りの退治機能部分をActionCableを利用してリアルタイムで情報が見れるようにする
（これに追加して誰かが退治開始した時に通知など送る機能があればさらによくなりそうですが、優先度は下げてOKです。）

また下記がコードで気になった点なので修正しておきましょう。
- Railsプロジェクトのコードをディレクトリをapiでまとめていますが、apiとして利用しないので、apiディレクトリをなくすか、他の名前にするようにしましょう。（現状ディレクトリでまとめる必要がないので、apiディレクトリをなくして、Railsプロジェクトコードを外に出しておきましょう）
- minitestを利用していないので、testディレクトリは削除しておきましょう。
- routingについて、`post /fight`と`patch /fight`は`resources :fights`の方でまとめられると思うのでこちらに合わせましょう！（意図があり、なぜこのようにしたのか説明できれば今のままでも問題ないです！）
- supports_controllerのデータをcreateとdestroyの処理はlikesと同じようにmodelメソッドに処理を切り出して利用するようにしましょう。
- posts_controllerのnewアクションで利用している`@tool`は利用していなさそうなので削除しておきましょう！（これから実装する場合であっても、何かしらの意図があり定義していると思われるので書かない方がいいですね）

### UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
下記に気になった点を挙げておくので、本リリースまでに修正ておきましょう。

- ゴキブリ対策一覧は情報量がある程度あった方が見栄えがいいので、他のユーザーに投稿を促すか、データとしてよくある対策一覧などは登録おくようにしましょう。
- マイページの階数が築年数の情報になっているので修正しておきましょう。
- TOPページの「ログインせずにはじめる」はログイン後は表示しないようにしましょう。
- 駆除中の仲間を見る導線がTOPページにしかなかったので、どのページからも見れるように導線を設けておきましょう。
- ヘッダーメニューがUIが統一されていないので統一させておきましょう。
  - 「ゴキブリ対策一覧/作成」と「対策道具、ログアウト」と「マイページアイコン」部分で分けられているので、1つにまとめるか種類ごとで分ける
- おすすめ対策道具一覧の中の「楽天市場をみる」ボタンは別タブで開くようにしましょう。
- 対策詳細画面の情報で反映していない部分があるので修正しておきましょう。（家屋、築年数、階数）
- 退治については文言を変えても良さそうですね、「退治を開始しました」はちょっと世界観が弱いので「退治開始！！！」的な感じでやる気が出るような文言と見た目を作るといいですね！
- 退治一覧で応援する場合のボタンが「いいね」なので、応援する意味合いのボタンのUIにするようにしましょう。

こちら内容確認いただき、各issueなどでタスク分割できましたら、このissue自体はcloseしてもらって大丈夫です。

また上記フィードバック内容を踏まえて、本リリースがいつ頃になりそうかの目安を教えていただければでございます！

**Comment by hagimoto0943** [comment]
レビューありがとうございます！
すべてissueに落とし込もました！
本リリースは8/4を目指して実装します！よろしくお願いします！
